model:
  arch: resnet56_cifar
  num_classes: 10
  shortcut: "B"   # 消融：把 CIFAR 的 A 换成投影 B，看效果差异（论文表明 A/B/C 差异不大）:contentReference[oaicite:9]{index=9}

data:
  name: cifar10
  root: ./data
  aug: strong

optim:
  name: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-4
  nesterov: true
  sched: cosine
  warmup_epochs: 5

train:
  epochs: 200
  batch_size: 128
  num_workers: 4
  amp: true
  clip_grad_norm: 1.0
  val_interval: 1
  out_dir: resnet_ablation/checkpoints/cifar10_resnet56_optB
  tb_dir: runs/cifar10_resnet56_optB
  seed: 42