model:
  arch: resnet50
  num_classes: 1000
  shortcut: "B"

data:
  name: imagenet
  root: /path/to/imagenet
  aug: standard

optim:
  name: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-4
  nesterov: true
  sched: multistep
  milestones: [30, 60, 90]
  gamma: 0.1

train:
  epochs: 120
  batch_size: 256
  num_workers: 8
  amp: true
  clip_grad_norm: 1.0
  val_interval: 1
  out_dir: resnet_ablation/checkpoints/imagenet_resnet50
  tb_dir: runs/imagenet_resnet50
  seed: 42